# Starship config

add_newline = false

[line_break]
disabled = true

[character]
success_symbol = '[#](bold green)'
error_symbol = '[#](bold red)'

[time]
disabled = true

[cmd_duration]
disabled = true
